name: JIRA Issue Transition

on:
  repository_dispatch:
    types:
      - jira_issue_transition
      
permissions:
  contents: write

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
         fetch-depth: 5

      - name: Get branch differences
        id: branch-diff
        run: |
          # Get the branch name
          currentBranch=$(git branch --show-current)
          
          # Check for differences between the pre-master branch and the 2 branch
          diff=$(git diff --name-only main...2 )
          echo "::set-output name=diff::$diff"

      - name: Check differences and update JIRA
        if: steps.branch-diff.outputs.diff != ''
        run: |
          # Extract issueKey from the payload
          issueKey=${{ github.event.client_payload.issueKey }}
          
          # Your JIRA API URL
          jiraUrl="https://gittest.atlassian.net/rest/api/3/issue/${issueKey}"
          
          # Your JIRA Custom Field ID
          customFieldId="customfield_10044"
          
          # JIRA username (email)
          jiraUsername="shoaib40ce@gmail.com"
          
          # JIRA API token or password
          jiraToken=${{ secrets.JIRA_API }}
          
          # Update the custom field using JIRA REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${jiraUsername}:${jiraToken}" \
            -d '{
              "fields": {
                "'${customFieldId}'": "tested"
              }
            }' \
            "${jiraUrl}"
