name: Update Jira Custom Field

on:
  repository_dispatch:  # This event will be triggered by the Jira webhook

jobs:
  update-field:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Jira Custom Field
        run: |
          # Parse the payload JSON to get necessary information
          ticket_id=$(echo "${{ github.event.client_payload.payload }}" | jq -r '.issue.id')
          transition=$(echo "${{ github.event.client_payload.payload }}" | jq -r '.transition.name')
          
          # Update the custom field using Jira REST API
          curl -D- -u $JIRA_USERNAME:$JIRA_TOKEN -X PUT \
            --data '{
              "fields": {
                "customfield_10037": "yes bainchod kaam kar rha hun"
              }
            }' -H "Content-Type: application/json" \
            https://testjiragitautomation.atlassian.net/rest/api/2/issue/SCRUM-17
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
