name: JIRA Transition Update

on:
  repository_dispatch:
    types:
      - jira.issue_transition

jobs:
  updateJiraCustomField:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update JIRA Custom Field
        env:
          JIRA_BASE_URL: 'https://testjiragitautomation.atlassian.net'
          JIRA_USERNAME: ${{ muhammadshoaibajk@gmail.com }}
          JIRA_TOKEN: ${{ ATATT3xFfGF0YxvyEEFeezKjbfe1Zhn8IVrCBFkGTH8TTjMqRa89nYRPV6Kif8Ep5it1MK_e6Jka9_BnyGvbssiuv04ur9zwie_KXmsB6ijtE7_hvU-8uF52ePZW7VHyVHNgdgx0gvdFu31FHQFF8OjYpz9v4AiXUKhIFPy806HN-kR6g3wamLU=57C12695}}
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }} # Update this if needed
          CUSTOM_FIELD_ID: 10037
        run: |
          # Extract ticket number from issue key
          ticket_number=$(echo "$ISSUE_KEY" | grep -oP '[A-Z]+-\d+')

          # Update custom field in JIRA using REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${JIRA_USERNAME}:${JIRA_TOKEN}" \
            -d '{
              "fields": {
                "customfield_'"$CUSTOM_FIELD_ID"'": "'"$ticket_number"'"
              }
            }' \
            "${JIRA_BASE_URL}/rest/api/2/issue/${ticket_number}"
