name: JIRA Issue Transition

on:
  pull_request:
    paths:
      - 'change.js'
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for differences in change.js
        id: check-diff
        run: |
          git fetch origin
          #Replace main with MAIN BRANCH
          git diff --quiet origin/main origin/${{ github.event.client_payload.issueKey }} -- change.js || echo "::set-output name=has_diff::true"

      - name: Update JIRA Custom Field
        if: steps.check-diff.outputs.has_diff == 'true'
        run: |
          # Extract issueKey from the payload
          issueKey=${{ github.event.client_payload.issueKey }}
          
          # Your JIRA API URL
          jiraUrl="https://gittest.atlassian.net/rest/api/3/issue/${issueKey}"
          
          # Your JIRA Custom Field ID
          customFieldId="customfield_10044"
          
          # JIRA username (email)
          jiraUsername="shoaib40ce@gmail.com"
          
          # JIRA API token or password
          jiraToken=${{ secrets.JIRA_API }}
          
          # Update the custom field using JIRA REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${jiraUsername}:${jiraToken}" \
            -d '{
              "fields": {
              # Replace "tested" with Custom message Required
                "'${customFieldId}'": "tested"
              }
            }' \
            "${jiraUrl}"
