name: Jira Ticket Transition

on:
  repository_dispatch:
    types:
      - jira.issue_transitioned

jobs:
  update_custom_field:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get ticket number
        uses: actions/github-script@v3
        with:
          script: |
            const ticketNumber = context.payload.issue.key;
            print(ticketNumber);

      - name: Get custom field value
        uses: jira-get-custom-field-value@v1
        with:
          issue: ${{ ticketNumber }}
          customFieldId: 10037

      - name: Update custom field value
        uses: jira-update-custom-field-value@v1
        with:
          issue: ${{ ticketNumber }}
          customFieldId: 10037
          value: ${{ steps.get_custom_field_value.outputs.value }}
