name: Update JIRA Custom Field

on:
  repository_dispatch:
    types:
      - jira.issue_transitioned

jobs:
  update_custom_field:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can change this to the version you want

      - name: Install dependencies
        run: npm install axios

      - name: Update JIRA Custom Field
        run: |
          # Extract necessary information from the event payload
          TICKET_NUMBER="${{ github.event.client_payload.ticket_number }}"
          CUSTOM_FIELD_ID="customfield_10037" # Replace with your custom field ID
          NEW_CUSTOM_FIELD_VALUE="New Value"  # Replace with the new value you want to set

          # Construct the JIRA API endpoint URL
          JIRA_API_URL="https://testjiragitautomation.atlassian.net/rest/api/3/issue/${TICKET_NUMBER}"

          # Prepare the JSON payload
          JSON_PAYLOAD='{
            "fields": {
              "'${CUSTOM_FIELD_ID}'": "'${NEW_CUSTOM_FIELD_VALUE}'"
            }
          }'

          # Make API request to update the custom field value using axios (Node.js)
          npx axios.put("${JIRA_API_URL}", ${JSON_PAYLOAD}, {
            auth: {
              username: "muhammadshoaibajk@gmail.com", // Replace with your JIRA email
              password: "ATATT3xFfGF0MsZE1cirJxVkX1B0dSskqdEvUJG0ZeV6PQBxzC7sg22e0rEc_jeaasfMAgoy4gkhYYZ0F8blgp2rKPUD8JUBWZtwwAy5Ihf1Iu-ish7zcggpoJFWisf7IFgkmh3-byFlP7YLWQZYFim1SycJ6fERYj7RWwROn3n8N1hTFeenJ5E=CAA656F8" // Replace with your JIRA API token
            },
            headers: {
              "Content-Type": "application/json"
            }
          })
