name: JIRA Issue Transition

on:
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        

      - name: Get branch names
        run: |
          MAIN_BRANCH="main"
          CURRENT_BRANCH="2"
          echo "MAIN_BRANCH=${MAIN_BRANCH}" >> $GITHUB_ENV
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV

      - name: Fetch branches
        run: |
          git fetch origin $MAIN_BRANCH
          git pull origin $CURRENT_BRANCH

      - name: Compare check.js between branches
        id: compare-branches
        run: |
          git checkout $CURRENT_BRANCH
          CHANGED_FILES=$(git diff $MAIN_BRANCH)
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Update JIRA Custom Field
        if: ${{ steps.compare-branches.outputs.CHANGED_FILES != '' }}
        run: |
          # Extract issueKey from the payload
          issueKey=${{ github.event.client_payload.issueKey }}
          
          # Your JIRA API URL
          jiraUrl="https://gittest.atlassian.net/rest/api/3/issue/${issueKey}"
          
          # Your JIRA Custom Field ID
          customFieldId="customfield_10044"
          
          # JIRA username (email)
          jiraUsername="shoaib40ce@gmail.com"
          
          # JIRA API token or password
          jiraToken=${{ secrets.JIRA_API }}
          
          # Update the custom field using JIRA REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${jiraUsername}:${jiraToken}" \
            -d '{
              "fields": {
                "'${customFieldId}'": "tested"
              }
            }' \
            "${jiraUrl}"
