name: Run On Issue Transition

on:
  repository_dispatch:
    types:
      - jira.issue_transitioned

jobs:
  run_api_js:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update JIRA Custom Field
        env:
          JIRA_BASE_URL: 'https://testjiragitautomation.atlassian.net'
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_TOKEN: ${{secrets.JIRA_TOKEN}}
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }} # Update this if needed
          CUSTOM_FIELD_ID: 10037
        run: |
          # Extract ticket number from issue key
          ticket_number=$(echo "$ISSUE_KEY" | grep -oP '[A-Z]+-\d+')

          # Update custom field in JIRA using REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${JIRA_USERNAME}:${JIRA_TOKEN}" \
            -d '{
              "fields": {
                "customfield_'"$CUSTOM_FIELD_ID"'": "'"$ticket_number"'"
              }
            }' \
            "${JIRA_BASE_URL}/rest/api/2/issue/${ticket_number}"
