name: Run On Issue Transition

on:
  repository_dispatch:
    types:
      - jira.issue_transitioned

jobs:
  run_api_js:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout FileTest repository
        uses: actions/checkout@v2
        with:
          repository: mshoaaaib/FlowTest
          path: FileTest  # Path to the directory where the repository will be checked out

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can change this to the version you want

      - name: Install dependencies
        run: npm install axios

      - name: Check for Changes
        id: check_changes
        run: |
          CHANGED_FILES=$(git -C FileTest diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'file.js' || echo "no_changes")
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run api.js if Changes
        run: |
          if [[ "${{ env.CHANGED_FILES }}" != "no_changes" ]]; then
            TICKET_NUMBER=$INPUT_TICKET_NUMBER
            node FileTest/file.js "$TICKET_NUMBER"
          else
            echo "No changes in the specified file."
          fi
        env:
          INPUT_TICKET_NUMBER: ${{ github.event.client_payload.ticket_number }}
