name: Update JIRA Custom Field

on:
  repository_dispatch:
    types:
      - jira.issue_transitioned

jobs:
  update-jira-field:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update JIRA Custom Field
        run: |
          curl -X PUT \
               -H "Content-Type: application/json" \
               -H "Authorization: Basic ${{ secrets.JIRA_TOKEN }}" \
               -d '{
                 "fields": {
                   "customfield_10037": "updated"
                 }
               }' \
               https://testjiragitautomation.atlassian.net/rest/api/3/issue/${{ github.event.client_payload.issue_id }}

