name: JIRA Issue Transition

on:
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List modified files
        id: list-files
        run: |
          git fetch origin
          # Replace main with MAIN BRANCH
          # Check for changes in the /server/models folder and ItemDefinition.ts file
          git diff --name-only origin/main origin/${{ github.event.client_payload.issueKey }} -- 'server/models/*' 'src/threatmodel/ItemDefinition.ts' > changed_files.txt
          echo "::set-output name=changed_files::$(cat changed_files.txt)"

      - name: Update JIRA Custom Field
        if: steps.list-files.outputs.changed_files != ''
        run: |
          # Extract issueKey from the payload
          issueKey=${{ github.event.client_payload.issueKey }}
          
          # Your JIRA API URL
          jiraUrl="https://gittest.atlassian.net/rest/api/3/issue/${issueKey}"
          
          # Your JIRA Custom Field ID
          customFieldId="customfield_10044"
          
          # JIRA username (email)
          jiraUsername="shoaib40ce@gmail.com"
          
          # JIRA API token or password
          jiraToken=${{ secrets.JIRA_API}}
          
          # Update the custom field using JIRA REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${jiraUsername}:${jiraToken}" \
            -d '{
              "fields": {
                "'${customFieldId}'": "Schema Change Detected"
              }
            }' \
            "${jiraUrl}"
