name: JIRA Transition Update

on:
  repository_dispatch:
    types:
      - jira.issue_transition

jobs:
  updateJiraCustomField:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update JIRA Custom Field
        env:
          JIRA_BASE_URL: ${{ https://testjiragitautomation.atlassian.net }}
          JIRA_USERNAME: ${{ muhammadshoaibajk@gmail.com }}
          JIRA_TOKEN: ${{ ATATT3xFfGF0MsZE1cirJxVkX1B0dSskqdEvUJG0ZeV6PQBxzC7sg22e0rEc_jeaasfMAgoy4gkhYYZ0F8blgp2rKPUD8JUBWZtwwAy5Ihf1Iu-ish7zcggpoJFWisf7IFgkmh3-byFlP7YLWQZYFim1SycJ6fERYj7RWwROn3n8N1hTFeenJ5E=CAA656F8 }}
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }}
          CUSTOM_FIELD_ID: 10037
        run: |
          # Extract ticket number from issue key
          ticket_number=$(echo "$ISSUE_KEY" | grep -oP '[A-Z]+-\d+')

          # Update custom field in JIRA using REST API
          curl -X PUT \
            -H "Content-Type: application/json" \
            -u "${JIRA_USERNAME}:${JIRA_TOKEN}" \
            -d '{
              "fields": {
                "customfield_'"$CUSTOM_FIELD_ID"'": "'"$ticket_number"'"
              }
            }' \
            "${JIRA_BASE_URL}/rest/api/2/issue/${ticket_number}"

# Make sure to replace the following secrets with your actual values:
# - JIRA_BASE_URL: Your JIRA base URL (e.g., https://your-company.atlassian.net)
# - JIRA_USERNAME: Your JIRA username or email
# - JIRA_TOKEN: An API token or password for authentication
